## Hi there 👋

<!--
**CXGMssdeyww/cxgmssdeyww** is a ✨ _special_ ✨ repository because its `README.md` (this file) appears on your GitHub profile.

Here are some ideas to get you started:

- 🔭 I’m currently working on ...
- 🌱 I’m currently learning ...
- 👯 I’m looking to collaborate on ...
- 🤔 I’m looking for help with ...
- 💬 Ask me about ...
- 📫 How to reach me: ...
- 😄 Pronouns: ...
- ⚡ Fun fact: ...
-->
![主页](https://github.com/CXGMssdeyww/cxgmssdeyww/blob/main/banner.jpg)
![内容1](https://raw.githubusercontent.com/CXGMssdeyww/cxgmssdeyww/refs/heads/main/photo1.jpg)
![内容2](https://raw.githubusercontent.com/CXGMssdeyww/cxgmssdeyww/refs/heads/main/photo2.jpg)
